name: Build ipq807x OpenWrt llvm toolchain
on:
   workflow_dispatch:
   push:
jobs:
    build:
        name: Build ipq807x OpenWrt llvm toolchain
        runs-on: ubuntu-24.04
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp .github/workflows/ipq807x openwrt/.config
                cd openwrt
                wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/15702.patch
                wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/15703.patch
                wget https://gist.githubusercontent.com/mj22226/562e59b54b4338d80ca82941ce7cf9b2/raw/bc8682e1455c652d8226cba08dfceae3c8318dbe/1817.patch
                git apply 15702.patch
                git apply 15703.patch
                git apply 1817.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                make defconfig
                make download -j32
                make tools/install -j4
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/qualcommax/ipq807x/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: ipq807x-18.1.8
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: IPQ807X LLVM TOOLCHAIN v18.1.8 ${{ env.D }}
                tag: ipq807x-18.1.8
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/qualcommax/ipq807x/*
