name: Build Rockchip OpenWrt llvm toolchain
on:
   workflow_dispatch:
   push:
jobs:
    build:
        name: Build OpenWrt llvm toolchain
        runs-on: ubuntu-24.04
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp .github/workflows/rockchip openwrt/.config
                cd openwrt
                wget https://gist.githubusercontent.com/mj22226/70d314fcabe2adcf4aa4ada578ecd784/raw/8092e732c83d16207db5864cb50cce67d6e745cd/1910.patch
                git apply 1910.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                make defconfig
                make download -j32
                make tools/install -j4
                make -j$(nproc) 'IGNORE_ERRORS=n m'  || true
                tar -czvf bin/targets/rockchip/armv8/logs.tar.gz logs
                rm -rf bin/targets/rockchip/armv8/packages || true
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: rockchip-19.1.0
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: ROCKCHIP LLVM TOOLCHAIN v19.1.0 ${{ env.D }}
                tag: rockchip-19.1.0
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*
